services:
  postgres:
    platform: linux/amd64
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456 
      POSTGRES_DB: expoferr
      SHARED_BUFFERS: 12GB
      WORK_MEM: 1GB
      EFFECTIVE_CACHE_SIZE: 12GB
      MAINTENANCE_WORK_MEM: 1GB
      TZ: America/Sao_Paulo
    volumes:
      - ./database/postgresql/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    cpus: "8.0"
    mem_limit: 20g
    mem_reservation: 2048m
    logging:
      driver: json-file
      options:
        max-size: "30m"
        max-file: "10"



volumes:
  postgres_data: